server:
  port: 8764

spring:
  application:
    name: eurekaclient
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    publisherConfirms: true
  zipkin:
    sender:
      type: web
  sleuth:
    sampler:
      probability: 0.9
    
song:
  name: song_client

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh

